version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./DB/mysql-data:/var/lib/mysql
      - ./DB:/docker-entrypoint-initdb.d
      - ./DB/bookData.csv:/tmp/bookData.csv
    command:
      - --secure-file-priv=/tmp
      - --local-infile=1

      
    restart: always

# volumes:
#   mysql-data:
